### ISSUE TITLE
Warnings when running commands from readme.md

### ISSUE THREAD

**Issue by Skeen** [valor-software/angular2-bootstrap-starter#2]
Hello,

When I run build / start commands described in the `readme.md`; I get several warnings (no errors);

* `npm i`:
```
...
> node-gyp rebuild

make: Entering directory 'PATH/node_modules/webpack-dev-server/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory 'PATH/node_modules/webpack-dev-server/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
npm WARN optional dep failed, continuing fsevents@1.0.2
...
```
* `tsd link`:
no warnings

* `npm start`:
```
...
WARNING in ../../node_modules/ng2-bootstrap/dist/module.d.ts
(2,19): Cannot find module 'index'. (2307)

WARNING in ./index.ts
(4,9): Module ''ng2-bootstrap'' has no exported member 'Alert'. (2305)

WARNING in ./index.ts
(4,16): Module ''ng2-bootstrap'' has no exported member 'Rating'. (2305)
webpack: bundle is now VALID.
...
```

System configuration;
* `node --version` --> `v4.1.1`
* `npm --version` --> `2.14.3`
* `git show | head -1` --> `commit df583038c7c39576352a4e7c28b04d401d14ba12`
* `uname -srvmo` --> `Linux 4.1.0-0.bpo.1-amd64 #1 SMP Debian 4.1.3-1~bpo8+1 (2015-08-12) x86_64 GNU/Linux`

Do note that the environment seems to be working, even when these errors are firing.

**Comment by valorkin** [comment]
@Skeen `npm` warning is fine, don't pay attention, only on errors
ng2-bootstrap updated to v 0.42 this one should be updated too
