### ISSUE TITLE
Add server example?

### ISSUE THREAD

**Issue by frankbenoit** [valor-software/angular2-bootstrap-starter#5]
Hi

Can you add example code, to have also backend code in this setup?
E.g. 
* having the backend also written in typescript
* sharing code with the frontend.
* webpack watching and reprocessing on file changes

thanks
Frank

**Comment by valorkin** [comment]
ok

**Comment by frankbenoit** [comment]
Meanwhile, i found angular2-minimalist-starter, which has exactly this.
Compared to your solution, it does not have ng2-bootstrap and does not use webpack.
Is it possible to have the best of both?

**Comment by valorkin** [comment]
link?

**Comment by frankbenoit** [comment]
This one:
https://github.com/rogerpadilla/angular2-minimalist-starter

**Comment by valorkin** [comment]
@frankbenoit can your PR change to readme including link to your repo?
