### ISSUE TITLE
[ts] Module '"project-name/node_modules/ng2-bootstrap/ng2-bootstrap"' has no exported member 'Alert'.

### ISSUE THREAD

**Issue by alexkibler** [valor-software/angular2-bootstrap-starter#98]
I just created a brand new `angular-cli` project and tried to import `ng2-bootstrap.`  

Here's my user configuration for `system-config.ts`:

```
/***********************************************************************************************
 * User Configuration.
 **********************************************************************************************/
/** Map relative paths to URLs. */
const map: any = {
  'ng2-bootstrap': 'vendor/ng2-bootstrap/components',
  'moment':'vendor/moment'
};

/** User packages configuration. */
const packages: any = {
  
    'vendor/ng2-bootstrap': {
      defaultExtension: 'js',           
    }
};
```

and I added `
      'ng2-bootstrap/**/*.js',
      'moment/moment.js'` to `angular-cli-build.js`

But whenever I try to `
import {Alert, DATEPICKER_DIRECTIVES} from 'ng2-bootstrap/ng2-bootstrap';`, I get the error listed in the title.

**Comment by valorkin** [comment]
Alert is AlertComponent now
